export const UNKNOWN_BRAND = 'Unknown';

export const KNOWN_BRANDS_MAP: Record<string, string> = {
  Repsol: 'Repsol',
  Galp: 'Galp',
  Moeve: 'Moeve',
  Cepsa: 'Cepsa',
  Bp: 'Bp',
  Ballenoil: 'Ballenoil',
  Plenergy: 'Plenergy',
  Shell: 'Shell',
  Prio: 'Prio',
  Petroprix: 'Petroprix',
  Petronor: 'Petronor',
  'Alves Bandeira': 'Alves Bandeira',
  Carrefour: 'Carrefour',
  Avia: 'Avia',
  Q8: 'Q8',
  Esclatoil: 'Esclatoil',
  Bonarea: 'Bonarea',
  Freitas: 'Freitas',
  Campsa: 'Campsa',
  Agla: 'Agla',
  Valcarce: 'Valcarce',
  Alcampo: 'Alcampo',
  Eni: 'Eni',
  Ham: 'Ham',
  Gasexpress: 'Gasexpress',
  Eroski: 'Eroski',
  Meroil: 'Meroil',
  'Pingo Doce': 'Pingo Doce',
  Beroil: 'Beroil',
  Auchan: 'Auchan',
  'Oz Energia': 'Oz Energia',
  Tamoil: 'Tamoil',
  Gaspe: 'Gaspe',
  Disa: 'Disa',
  Molgas: 'Molgas',
  Ids: 'Ids',
  Naturgy: 'Naturgy',
  Iberdoex: 'Iberdoex',
  Nieves: 'Nieves',
  Autonetoil: 'Autonetoil',
  Leclerc: 'Leclerc',
  'Asc Carburantes': 'Asc Carburantes',
  Easygas: 'Easygas',
  Petrocat: 'Petrocat',
  Agropal: 'Agropal',
  'Rede Energia': 'Rede Energia',
  Petromiralles: 'Petromiralles',
  'Gm Oil': 'Gm Oil',
  Tfuel: 'Tfuel',
  Libre: 'Libre',
  Pcan: 'Pcan',
  Nova: 'Nova',
  'Auto Julio': 'Auto Julio',
  'Family Energy': 'Family Energy',
  'Confort Auto': 'Confort Auto',
  Gmoil: 'Gmoil',
  Blanca: 'Blanca',
  Dst: 'Dst',
  Supeco: 'Supeco',
  T9: 'T9',
  Bxpress: 'Bxpress',
  'Fast Fuel': 'Fast Fuel',
  'Carlos Baltazar': 'Carlos Baltazar',
  'Dourogas Natural': 'Dourogas Natural',
  Bdmed: 'Bdmed',
  Mlc: 'Mlc',
  Staroil: 'Staroil',
  'Gasoleos Teruel': 'Gasoleos Teruel',
  Tuacar: 'Tuacar',
  'Autonet&oil': 'Autonet&oil',
  Nuroil: 'Nuroil',
  Nafte: 'Nafte',
  Geds: 'Geds',
  Petrem: 'Petrem',
  Gasolwin: 'Gasolwin',
  Recheio: 'Recheio',
  'V2 Gasolineras': 'V2 Gasolineras',
  'Energy Carburantes': 'Energy Carburantes',
  Euskadilowcost: 'Euskadilowcost',
  'Las Palmeras': 'Las Palmeras',
  'Just Fuel': 'Just Fuel',
  'Euronor Energy': 'Euronor Energy',
  Econoil: 'Econoil',
  'Paso Honroso': 'Paso Honroso',
  Alas: 'Alas',
  Ecobrent: 'Ecobrent',
  'Para Y Sigue': 'Para Y Sigue',
  Campoastur: 'Campoastur',
  'Petrolis Independents - Petro7': 'Petrolis Independents - Petro7',
  Lowcostfuel: 'Lowcostfuel',
  Oilprix: 'Oilprix',
  'Aliara Energia': 'Aliara Energia',
  'Seroil Energy': 'Seroil Energy',
  'Sis Carburantes': 'Sis Carburantes',
  'Ortegal Oil': 'Ortegal Oil',
  Sbc: 'Sbc',
  Deoil: 'Deoil',
  'Adelfas Oil': 'Adelfas Oil',
  Dpp: 'Dpp',
  'G-Energy': 'G-Energy',
  Inpealsa: 'Inpealsa',
  Repostando: 'Repostando',
  'b Energias': 'b Energias',
  Eurocam: 'Eurocam',
  Repostar: 'Repostar',
  Evolution: 'Evolution',
  Petrolowcost: 'Petrolowcost',
  Benzoil: 'Benzoil',
  'Aneu Oil': 'Aneu Oil',
  Costco: 'Costco',
  'Urban Oil': 'Urban Oil',
  Hemegas: 'Hemegas',
  'Petrol & Go': 'Petrol & Go',
  'Sin Rotulo': 'Sin Rotulo',
  'Hafesa Oil': 'Hafesa Oil',
  Santiago: 'Santiago',
  Minioil: 'Minioil',
  Jaencoop: 'Jaencoop',
  Ibessa: 'Ibessa',
  Transforpel: 'Transforpel',
  Petrin: 'Petrin',
  Via: 'Via',
  'Avanza Oil': 'Avanza Oil',
  'Global Oil': 'Global Oil',
  Rhr: 'Rhr',
  Gugas: 'Gugas',
  'La Estrella De Qatar': 'La Estrella De Qatar',
  'Star Petroleum': 'Star Petroleum',
  'Petro Valles': 'Petro Valles',
  'Petrolis Independents': 'Petrolis Independents',
  'Zona Diesel': 'Zona Diesel',
  Biesa: 'Biesa',
  Enerplus: 'Enerplus',
  'Bs Energy': 'Bs Energy',
  Maxpetrol: 'Maxpetrol',
  Spl: 'Spl',
  'Icor Energia': 'Icor Energia',
  'Full & Go': 'Full & Go',
  'Carrasquinho & Filhos': 'Carrasquinho & Filhos',
  Petrovaz: 'Petrovaz',
  Beq: 'Beq',
  Fth: 'Fth',
  'Avanza Energy': 'Avanza Energy',
  Petroenergy: 'Petroenergy',
  'Panaway Road': 'Panaway Road',
  Suimasa: 'Suimasa',
  Andamur: 'Andamur',
  Adelfas: 'Adelfas',
  'Valcor Sociedad Cooperativa Asturiana': 'Valcor Sociedad Cooperativa Asturiana',
  Lukoil: 'Lukoil',
  Luxoil: 'Luxoil',
  'Gm Fuel Stations': 'Gm Fuel Stations',
  Sorligo: 'Sorligo',
  Vilalta: 'Vilalta',
  Ayafuel: 'Ayafuel',
  Vilacarburants: 'Vilacarburants',
  'Feixas Aulet': 'Feixas Aulet',
  'Petrolis De Barcelona': 'Petrolis De Barcelona',
  'El Surtidor': 'El Surtidor',
  'Pandora Energy': 'Pandora Energy',
  'Low Cost Fuel': 'Low Cost Fuel',
  Ninguno: 'Ninguno',
  Buquerin: 'Buquerin',
  No: 'No',
  'Clc Calidad Low Cost': 'Clc Calidad Low Cost',
  'Suministros Mazo': 'Suministros Mazo',
  Sp: 'Sp',
  'Petrol&go': 'Petrol&go',
  Masoil: 'Masoil',
  Fueling: 'Fueling',
  'Low Cost Repost': 'Low Cost Repost',
  'Petro Swap': 'Petro Swap',
  Petrolis: 'Petrolis',
  Laboil: 'Laboil',
  'Ponent Energia': 'Ponent Energia',
  Lavaplus: 'Lavaplus',
  'El Trebol': 'El Trebol',
  Octanos: 'Octanos',
  Arrossaires: 'Arrossaires',
  Nuboil: 'Nuboil',
  Navamuel: 'Navamuel',
  Gasolben: 'Gasolben',
  Petromar: 'Petromar',
  Esso: 'Esso',
  Gasolar: 'Gasolar',
  'Petro Basto': 'Petro Basto',
  Flua: 'Flua',
  Redil: 'Redil',
  Pronto: 'Pronto',
  'A&a': 'A&a',
  Gasplay: 'Gasplay',
  'Galera Areas De Servicio': 'Galera Areas De Servicio',
  'Avanza Low Cost': 'Avanza Low Cost',
  'Gasoleo Expres': 'Gasoleo Expres',
  Gasden: 'Gasden',
  Mora: 'Mora',
  'Low Cost 24h': 'Low Cost 24h',
  Sectoroil: 'Sectoroil',
  Campoejido: 'Campoejido',
  Hafesa: 'Hafesa',
  Ads: 'Ads',
  'Ona Lowcost': 'Ona Lowcost',
  Norpetrol: 'Norpetrol',
  'Zepxa Eco': 'Zepxa Eco',
  'Esc-Petroleos': 'Esc-Petroleos',
  Esoil: 'Esoil',
  'El Centro': 'El Centro',
  Saras: 'Saras',
  Alimerka: 'Alimerka',
  'Pandora Bioenergy Sl': 'Pandora Bioenergy Sl',
  'Fernandez Bermejo': 'Fernandez Bermejo',
  'M&d': 'M&d',
  Si: 'Si',
  Petrogold: 'Petrogold',
  'San Isidro': 'San Isidro',
  Petrocar: 'Petrocar',
  'San Agustin De Obando Scl': 'San Agustin De Obando Scl',
  Qualityfuel: 'Qualityfuel',
  'Petrostar Energia': 'Petrostar Energia',
  'Set&go': 'Set&go',
  'Baltran S.a': 'Baltran S.a',
  Premira: 'Premira',
  Bonoil: 'Bonoil',
  Gratsa: 'Gratsa',
  Tortuga: 'Tortuga',
  Qoil: 'Qoil',
  'Oil Prix': 'Oil Prix',
  Total: 'Total',
  'La Panadella': 'La Panadella',
  Lacicar: 'Lacicar',
  Esser: 'Esser',
  'Amat Oil': 'Amat Oil',
  Express: 'Express',
  Urkioil: 'Urkioil',
  Frii: 'Frii',
  Clc: 'Clc',
  Agrocantabria: 'Agrocantabria',
  'Area De Servicio Ural': 'Area De Servicio Ural',
  'L\'area': 'L\'area',
  'Face Petroleum': 'Face Petroleum',
  'Gasoelectric Low Cost': 'Gasoelectric Low Cost',
  'Red Car Oil': 'Red Car Oil',
  On365: 'On365',
  Hgoil: 'Hgoil',
  'Energias Af': 'Energias Af',
  Atenoil: 'Atenoil',
  Cooperativa: 'Cooperativa',
  'Bqp Fuel': 'Bqp Fuel',
  Petromarkt: 'Petromarkt',
  Petrosol: 'Petrosol',
  'M3 Petroleos': 'M3 Petroleos',
  Clun: 'Clun',
  Petrocash: 'Petrocash',
  'Cc Oil': 'Cc Oil',
  'Gv Oil': 'Gv Oil',
  Ponteulla: 'Ponteulla',
  'Onroad 24': 'Onroad 24',
  'Fuel Truck': 'Fuel Truck',
  Condis: 'Condis',
  'Poste De Mata': 'Poste De Mata',
  Gadcar: 'Gadcar',
  Petroselva: 'Petroselva',
  Globaltank: 'Globaltank',
  'E.s. Mirasierra': 'E.s. Mirasierra',
  'Combustibles Gomez': 'Combustibles Gomez',
  Mc: 'Mc',
  'Smart Oil': 'Smart Oil',
  'Simon Grup': 'Simon Grup',
  Primafrio: 'Primafrio',
  Coloso: 'Coloso',
  Mazana: 'Mazana',
  'Orellana Perdiz': 'Orellana Perdiz',
  Codo_cm: 'Codo_cm',
  Guay: 'Guay',
  'Low Cost 24': 'Low Cost 24',
  'Coop.juncosa': 'Coop.juncosa',
  Blanco: 'Blanco',
  Henergy: 'Henergy',
  Dinergia: 'Dinergia',
  Gueroil: 'Gueroil',
  Anibal: 'Anibal',
  '24h': '24h',
  'Roymaga Petroleos,sl': 'Roymaga Petroleos,sl',
  'Roymaga Petroleos': 'Roymaga Petroleos',
  Renesur: 'Renesur',
  Alimer: 'Alimer',
  'Izelai Fuel': 'Izelai Fuel',
  Noil: 'Noil',
  Aralar: 'Aralar',
  'Gasoleos Mercadaiz': 'Gasoleos Mercadaiz',
  'Trueba Energy': 'Trueba Energy',
  'Santana Dominguez': 'Santana Dominguez',
  Crp: 'Crp',
  Cobideza: 'Cobideza',
  Gvoil: 'Gvoil',
  Gaslander: 'Gaslander',
  Sertuy: 'Sertuy',
  Pgs: 'Pgs',
  'G Cantalejo': 'G Cantalejo',
  Moove: 'Moove',
  'Tj Oil': 'Tj Oil',
  'El Mayoria Combustibles': 'El Mayoria Combustibles',
  Gashome: 'Gashome',
  Campo: 'Campo',
  Montsia: 'Montsia',
  Coperal: 'Coperal',
  Exoil: 'Exoil',
  'Agudo Gasoleos': 'Agudo Gasoleos',
  Bermudez: 'Bermudez',
  'Hnos.fernandez': 'Hnos.fernandez',
  'Gamba Oil': 'Gamba Oil',
  Stels: 'Stels',
  Duroil: 'Duroil',
  Autoil: 'Autoil',
  'Rural San Vicente Ferrer': 'Rural San Vicente Ferrer',
  Benzina: 'Benzina',
  'Peymon Oil S.l': 'Peymon Oil S.l',
  Sel: 'Sel',
  'Gasoleos La Eliana': 'Gasoleos La Eliana',
  Rapidfuel: 'Rapidfuel',
  'Texako Trucks': 'Texako Trucks',
  Fertiblend: 'Fertiblend',
  Agrinza: 'Agrinza',
  Bola: 'Bola',
  'Coop. Virgen Oliva': 'Coop. Virgen Oliva',
  'Cidade N\'aldeia': 'Cidade N\'aldeia',
  Petrovariante: 'Petrovariante',
  Sopor: 'Sopor',
  Creixoauto: 'Creixoauto',
  Etc: 'Etc',
  'Vmf Energia': 'Vmf Energia',
  Gapor: 'Gapor',
  'Nº 10.935': 'Nº 10.935',
  'La Pulgosa': 'La Pulgosa',
  Petrocamp: 'Petrocamp',
  P347: 'P347',
  Lozano: 'Lozano',
  'Enercom Carburantes': 'Enercom Carburantes',
  'La Gaviota Gasolinera 24 Hora': 'La Gaviota Gasolinera 24 Hora',
  'Fast & Gas': 'Fast & Gas',
  'Area Los Llanos': 'Area Los Llanos',
  'El Jucar': 'El Jucar',
  'Gasolinera Low Cost Penades': 'Gasolinera Low Cost Penades',
  'Quality Almansa': 'Quality Almansa',
  'Gasolineras Del Rey': 'Gasolineras Del Rey',
  'Vila Y Fayos': 'Vila Y Fayos',
  Dlp: 'Dlp',
  'Nº 7374': 'Nº 7374',
  'Es San Antonioabad. Fuentealbilla': 'Es San Antonioabad. Fuentealbilla',
  Petrogas: 'Petrogas',
  'E.s. Letur': 'E.s. Letur',
  'Los Corrales': 'Los Corrales',
  'Gasoleos Turbula': 'Gasoleos Turbula',
  'Sat Santa Cruz De Pozo Lorente': 'Sat Santa Cruz De Pozo Lorente',
  Canoil: 'Canoil',
  'La Remediadora': 'La Remediadora',
  'Navarro Y Valero, S.l': 'Navarro Y Valero, S.l',
  'La Gaviota Gasolineras': 'La Gaviota Gasolineras',
  'E.s. Tobarra': 'E.s. Tobarra',
  'Ntra. Sra. De La Encarnacion': 'Ntra. Sra. De La Encarnacion',
  'E.s El Gorrion': 'E.s El Gorrion',
  Champinter: 'Champinter',
  'Bodegas Saac': 'Bodegas Saac',
  'Suver Gasoleos': 'Suver Gasoleos',
  'Gasolinera Alcoy': 'Gasolinera Alcoy',
  Goteta: 'Goteta',
  'Vcc Alicante': 'Vcc Alicante',
  'E.s. Santa Faz': 'E.s. Santa Faz',
  Aquavel: 'Aquavel',
  Parcelogic: 'Parcelogic',
  Atalayas: 'Atalayas',
  'Las Maromas': 'Las Maromas',
  Levantina: 'Levantina',
  'Gasolinera Aspe': 'Gasolinera Aspe',
  'Fuspra Energy': 'Fuspra Energy',
  'Vcc Anouer': 'Vcc Anouer',
  Beniexpress: 'Beniexpress',
  'Vcc Benissa': 'Vcc Benissa',
  Rosello: 'Rosello',
  Bigasoil: 'Bigasoil',
  'Ritor Diesel': 'Ritor Diesel',
  'Cofradia De Pescadores': 'Cofradia De Pescadores',
  'Calpe Automocion Ii': 'Calpe Automocion Ii',
  'Calpe Automocion': 'Calpe Automocion',
  Drz: 'Drz',
  Luzoil: 'Luzoil',
  Briogas: 'Briogas',
  'Futura Petrolium': 'Futura Petrolium',
  'La 23': 'La 23',
  'Pepe Ramon': 'Pepe Ramon',
  'E.s Denia': 'E.s Denia',
  Teckmar: 'Teckmar',
  Mayayo: 'Mayayo',
  'La Estacion': 'La Estacion',
  'E.s. El Poligono': 'E.s. El Poligono',
  'E.s. Plusoil': 'E.s. Plusoil',
  Petroalacant: 'Petroalacant',
  'Marina De La Plana': 'Marina De La Plana',
  'Gasolinera De Formentera': 'Gasolinera De Formentera',
  Josberfuel: 'Josberfuel',
  'Seven Oil': 'Seven Oil',
  'Santa Cruz': 'Santa Cruz',
  Neft: 'Neft',
  'E.s. Texas': 'E.s. Texas',
  'Petranoil Station': 'Petranoil Station',
  'T. Albero': 'T. Albero',
  'El Canari Onil': 'El Canari Onil',
  Gasorba: 'Gasorba',
  Revisoil: 'Revisoil',
  Vegara: 'Vegara',
  'El Tanque': 'El Tanque',
  'Combustibles La Murada': 'Combustibles La Murada',
  Combusella: 'Combusella',
  Coopego: 'Coopego',
  'E.s.horadada': 'E.s.horadada',
  'E.s. La Torre': 'E.s. La Torre',
  Ghol: 'Ghol',
  'Estacion De Servicio Petroblue': 'Estacion De Servicio Petroblue',
  'Santa Pola': 'Santa Pola',
  'Low Cost': 'Low Cost',
  Polagas: 'Polagas',
  'La Hita - Torrevieja': 'La Hita - Torrevieja',
  'E.s. Las Salinas': 'E.s. Las Salinas',
  'Quality Oil': 'Quality Oil',
  Petrolavila: 'Petrolavila',
  Ht: 'Ht',
  'La Morenica': 'La Morenica',
  Jbm: 'Jbm',
  Campoadra: 'Campoadra',
  'Carburantes Filabres': 'Carburantes Filabres',
  'Carburantes Almanzora Sl': 'Carburantes Almanzora Sl',
  Transrumar: 'Transrumar',
  'E.s.terdiguera': 'E.s.terdiguera',
  'Raspaoil Almeria': 'Raspaoil Almeria',
  'Ciudad Del Taxi': 'Ciudad Del Taxi',
  'La Torre': 'La Torre',
  'E.s. Alvamar': 'E.s. Alvamar',
  Jcarrion: 'Jcarrion',
  'Isabel Alonso': 'Isabel Alonso',
  'Hnos.martinez': 'Hnos.martinez',
  'E.s.arboleas': 'E.s.arboleas',
  Truckstop: 'Truckstop',
  'Es Vefruber': 'Es Vefruber',
  'Carburantes De Cantoria': 'Carburantes De Cantoria',
  'Indapak Logistics': 'Indapak Logistics',
  'Es Borja - E.s.sobrado De Picato, S.l.u': 'Es Borja - E.s.sobrado De Picato, S.l.u',
  'A.s. El Artinero': 'A.s. El Artinero',
  'Truck Stop Dalias': 'Truck Stop Dalias',
  'E.s. Campejido Dalias': 'E.s. Campejido Dalias',
  'Ciudad Ejido,s.l': 'Ciudad Ejido,s.l',
  'Gasolinera El Ejido': 'Gasolinera El Ejido',
  'E.s. Coop Santa Maria Del Aguila - El Ejido': 'E.s. Coop Santa Maria Del Aguila - El Ejido',
  'Es Norias': 'Es Norias',
  'Ejido Oeste': 'Ejido Oeste',
  'Bahia De Almerimar': 'Bahia De Almerimar',
  Indasol: 'Indasol',
  Splash: 'Splash',
  'Truck Stop Del Poniente': 'Truck Stop Del Poniente',
  Econorias: 'Econorias',
  'Es Fepsa  La Palma': 'Es Fepsa  La Palma',
  'Cohorsan Sca': 'Cohorsan Sca',
  'E.s.balermamar S.c.a': 'E.s.balermamar S.c.a',
  'La Tarambana': 'La Tarambana',
  'Coop. Tracomar': 'Coop. Tracomar',
  'Coaltrans S Coop And': 'Coaltrans S Coop And',
  'Oil Jcj': 'Oil Jcj',
  'E.s H8 Energys': 'E.s H8 Energys',
  'Iniciativas Rumial': 'Iniciativas Rumial',
  'Ntra Sra Del Rosario': 'Ntra Sra Del Rosario',
  'Litoral De Nijar': 'Litoral De Nijar',
  'Ee.ss. San Sebastian': 'Ee.ss. San Sebastian',
  Europulpi: 'Europulpi',
  'E.s. Aquacenter': 'E.s. Aquacenter',
  'Costa De Almeria': 'Costa De Almeria',
  'E.s Pacocalcula': 'E.s Pacocalcula',
  'E/s  San Javier': 'E/s  San Javier',
  'Citrasor, Sca': 'Citrasor, Sca',
  'Los Filabres Sca': 'Los Filabres Sca',
  'Desert Truckers': 'Desert Truckers',
  Volacan: 'Volacan',
  Anroroil: 'Anroroil',
  Topfuel: 'Topfuel',
  'Estacion De Servicio Velez Rubio': 'Estacion De Servicio Velez Rubio',
  'Las Pepas': 'Las Pepas',
  'Baraza+': 'Baraza+',
  Veradiesel: 'Veradiesel',
  Vulco: 'Vulco',
  'S.a.t. Pisaica De La Virgen': 'S.a.t. Pisaica De La Virgen',
  Consumomar: 'Consumomar',
  'E.s.vicasol': 'E.s.vicasol',
  'Oil Barol Sl': 'Oil Barol Sl',
  'Estaciones Gb': 'Estaciones Gb',
  Gerantisan: 'Gerantisan',
  'E.s. Tocalu': 'E.s. Tocalu',
  'Eess Dyneff': 'Eess Dyneff',
  Onroad24: 'Onroad24',
  Armentia: 'Armentia',
  'Onaindia Lowcost': 'Onaindia Lowcost',
  Onaindia: 'Onaindia',
  N1jundiz: 'N1jundiz',
  'Ibaia Energy': 'Ibaia Energy',
  'E.s. Cristaleria': 'E.s. Cristaleria',
  Gf: 'Gf',
  Mp: 'Mp',
  Valcor: 'Valcor',
  Solras: 'Solras',
  Washmax: 'Washmax',
  Innogas: 'Innogas',
  Empresoil: 'Empresoil',
  'El Salvador': 'El Salvador',
  'Dismusa Masymas': 'Dismusa Masymas',
  Dismusa: 'Dismusa',
  Castronalon: 'Castronalon',
  'Asipo Servicios': 'Asipo Servicios',
  'Posada Menendez': 'Posada Menendez',
  'E.s.la Colorada': 'E.s.la Colorada',
  Petronora: 'Petronora',
  Arbesu: 'Arbesu',
  'Ee Ss Somiedo': 'Ee Ss Somiedo',
  'La Adrada': 'La Adrada',
  'San Juan De La Cruz': 'San Juan De La Cruz',
  'An Energeticos - Madrigal': 'An Energeticos - Madrigal',
  Mingorria: 'Mingorria',
  Autoservicio: 'Autoservicio',
  Goexpress: 'Goexpress',
  'E.s Gredos': 'E.s Gredos',
  Gaslowcost: 'Gaslowcost',
  'Las Correhuelas, S.l': 'Las Correhuelas, S.l',
  'Coop.guadalperales': 'Coop.guadalperales',
  'Morgane Oil': 'Morgane Oil',
  'Gasolinera San Roque': 'Gasolinera San Roque',
  Qfuel: 'Qfuel',
  Noroil: 'Noroil',
  'Eess La Florida': 'Eess La Florida',
  'Coop. Perales': 'Coop. Perales',
  Sea: 'Sea',
  'Cg Carburantes Azuaga': 'Cg Carburantes Azuaga',
  'Ocho Areas De Servicio': 'Ocho Areas De Servicio',
  'Area San Martin': 'Area San Martin',
  Bds: 'Bds',
  Nakanoil: 'Nakanoil',
  'Estrella Roja': 'Estrella Roja',
  'Rock & Oil': 'Rock & Oil',
  Petromode: 'Petromode',
  'S. Coop. Agricola De Colonos De Novelda': 'S. Coop. Agricola De Colonos De Novelda',
  Talantena: 'Talantena',
  'E.s.san Benito': 'E.s.san Benito',
  'E.s Tentudia': 'E.s Tentudia',
  'Laencina Sodad Coop Limitada': 'Laencina Sodad Coop Limitada',
  'Carburantes Gb': 'Carburantes Gb',
  'Pk 11': 'Pk 11',
  'Coagcor A.i.e': 'Coagcor A.i.e',
  Donbex: 'Donbex',
  Casat: 'Casat',
  'Gc Energy': 'Gc Energy',
  'Logistica Moreno': 'Logistica Moreno',
  'Gasoleo B': 'Gasoleo B',
  Sangar: 'Sangar',
  Impulso365: 'Impulso365',
  'Sdad.coop.limt. De Hornachos': 'Sdad.coop.limt. De Hornachos',
  'Murillo Rojo Sl': 'Murillo Rojo Sl',
  'San Cristobal': 'San Cristobal',
  Petrocor: 'Petrocor',
  'Fuel 10': 'Fuel 10',
  'Verde Y Sostenible': 'Verde Y Sostenible',
  Comosurex: 'Comosurex',
  'La Milagrosa': 'La Milagrosa',
  Tierrasgordas: 'Tierrasgordas',
  'Asaja Sdad Coop': 'Asaja Sdad Coop',
  'Explotaciones Gasoal': 'Explotaciones Gasoal',
  Mercoenergy: 'Mercoenergy',
  'Sdad. Coop. Vegas Bajas': 'Sdad. Coop. Vegas Bajas',
  'Ntra Sra De Belen': 'Ntra Sra De Belen',
  Fuelquin: 'Fuelquin',
  'Sdad.coop.olivareros Y Viticultores': 'Sdad.coop.olivareros Y Viticultores',
  Joymar: 'Joymar',
  'C.t. De San Vicente De Alcantara': 'C.t. De San Vicente De Alcantara',
  'Amalia De Sajonia': 'Amalia De Sajonia',
  'Carburantes La Estrella': 'Carburantes La Estrella',
  Agrosola: 'Agrosola',
  'E/s Talavera': 'E/s Talavera',
  Copttraba: 'Copttraba',
  Doex: 'Doex',
  Moreno: 'Moreno',
  Valencioil: 'Valencioil',
  'E.s. La Coronada': 'E.s. La Coronada',
  13344: '13344',
  Canchalosa: 'Canchalosa',
  'Buga 2000': 'Buga 2000',
  'Economic Fuel': 'Economic Fuel',
  'Las Gaviotas': 'Las Gaviotas',
  Petromareswagen: 'Petromareswagen',
  Fitogas: 'Fitogas',
  'M Automocion': 'M Automocion',
  Petrozal: 'Petrozal',
  'E.s.moianes': 'E.s.moianes',
  Gardenoil: 'Gardenoil',
  'Garatge Horta': 'Garatge Horta',
  'Estacion De Servicio Favencia Julia': 'Estacion De Servicio Favencia Julia',
  'Premium Energy La Sagrera': 'Premium Energy La Sagrera',
  'Ballus Baix Cost': 'Ballus Baix Cost',
  'Estacio Servei Bigues I Riells': 'Estacio Servei Bigues I Riells',
  'Es Calders': 'Es Calders',
  Sparoil: 'Sparoil',
  Avanti: 'Avanti',
  Petroeight: 'Petroeight',
  'Parking Service Castellbisbal, Sa': 'Parking Service Castellbisbal, Sa',
  'Benzinera Castellbisbal': 'Benzinera Castellbisbal',
  Fercam: 'Fercam',
  'Premium Energy Castelldefels': 'Premium Energy Castelldefels',
  Porbol: 'Porbol',
  'Petrologic Oil': 'Petrologic Oil',
  'Es Parking Del Baix Llobregat': 'Es Parking Del Baix Llobregat',
  Gasuir: 'Gasuir',
  'Benzinera La Garriga': 'Benzinera La Garriga',
  'Gasoil 3b': 'Gasoil 3b',
  Cacenca: 'Cacenca',
  'E.s.gelida': 'E.s.gelida',
  '1primer': '1primer',
  'Benzinera Granollers': 'Benzinera Granollers',
  'Nevada Energia': 'Nevada Energia',
  'Estacio Servei Can Buxeres': 'Estacio Servei Can Buxeres',
  'Portuarios Servicios': 'Portuarios Servicios',
  Ecobenz: 'Ecobenz',
  'Petro G24': 'Petro G24',
  Mestrans: 'Mestrans',
  'Fer Preu Just': 'Fer Preu Just',
  'By Energy': 'By Energy',
  'Estacio Servei Llinars': 'Estacio Servei Llinars',
  'Hicap Energy': 'Hicap Energy',
  Petroset: 'Petroset',
  'Pedrosa Center': 'Pedrosa Center',
  Mataro: 'Mataro',
  'Serviauto Ecologic': 'Serviauto Ecologic',
  'Area Diesel': 'Area Diesel',
  'Good Price Palau': 'Good Price Palau',
  Couso: 'Couso',
  Petro7: 'Petro7',
  'E.s. Pineda De Mar': 'E.s. Pineda De Mar',
  'Es Adenor Polinya': 'Es Adenor Polinya',
  'Ballus Baixcost': 'Ballus Baixcost',
  'Punta Solera': 'Punta Solera',
  Euronor: 'Euronor',
  'Servicios Petroliferos': 'Servicios Petroliferos',
  'E.s. Rosaleda  -st. Fruitos De Bages-     Gasoils Rovira': 'E.s. Rosaleda  -st. Fruitos De Bages-     Gasoils Rovira',
  'Carburants Sant Iscle': 'Carburants Sant Iscle',
  '3 Punt Tres': '3 Punt Tres',
  Muxu: 'Muxu',
  'Bright Service': 'Bright Service',
  'E.s. Sant Marti D\'albars': 'E.s. Sant Marti D\'albars',
  Nada: 'Nada',
  Wences: 'Wences',
  'Pins Oil': 'Pins Oil',
  'Benzinera Santa Susanna': 'Benzinera Santa Susanna',
  'Area De Serveis Taradell,sl': 'Area De Serveis Taradell,sl',
  Cobasa: 'Cobasa',
  Octopo: 'Octopo',
  'La Farinera': 'La Farinera',
  Petroalfa: 'Petroalfa',
  'Primer- Area Vic': 'Primer- Area Vic',
  'Primer Truck Area': 'Primer Truck Area',
  'Zd Urban Vic': 'Zd Urban Vic',
  'Benzineres Montoil': 'Benzineres Montoil',
  'Servicios Penedes Sa': 'Servicios Penedes Sa',
  'E.s.el Campillo': 'E.s.el Campillo',
  'Zabalgarbi Gnc': 'Zabalgarbi Gnc',
  'Zelai Luzea': 'Zelai Luzea',
  Arribide: 'Arribide',
  Bideko: 'Bideko',
  Epermendi: 'Epermendi',
  Gamiz: 'Gamiz',
  Petroencina: 'Petroencina',
  Z2oil: 'Z2oil',
  'Gasolinera Zamudio': 'Gasolinera Zamudio',
  Portuoil: 'Portuoil',
  Dgv: 'Dgv',
  'Gasoleos Aranda': 'Gasoleos Aranda',
  'E.s.ferreira': 'E.s.ferreira',
  'Suministros Agrobureba, Sl': 'Suministros Agrobureba, Sl',
  Villalonquejar: 'Villalonquejar',
  'Las Terrazas': 'Las Terrazas',
  Trifon: 'Trifon',
  Urlave: 'Urlave',
  Carcedoil: 'Carcedoil',
  'Ez Energy': 'Ez Energy',
  Tenergy: 'Tenergy',
  'E.s. Las Brujas - Cernegula': 'E.s. Las Brujas - Cernegula',
  'Es Hermanos Olalla': 'Es Hermanos Olalla',
  Coridu: 'Coridu',
  Tobalinoil: 'Tobalinoil',
  'Coop. Arlanza': 'Coop. Arlanza',
  'E.s.saiz': 'E.s.saiz',
  'E.s. Rivera': 'E.s. Rivera',
  'Magna Oil': 'Magna Oil',
  'Gasolinera Los Ibores': 'Gasolinera Los Ibores',
  Cooprado: 'Cooprado',
  'San Roque': 'San Roque',
  Copal: 'Copal',
  'Soc Coop Ntra Sra Del Prado S.c': 'Soc Coop Ntra Sra Del Prado S.c',
  Batan: 'Batan',
  'Aceitunera Granadilla': 'Aceitunera Granadilla',
  'Petrol Station': 'Petrol Station',
  Pocito: 'Pocito',
  'Carburantes Coolosar': 'Carburantes Coolosar',
  'E.s. Comarca De La Vera': 'E.s. Comarca De La Vera',
  'Coop. Ntra Sra Del Prado S.c': 'Coop. Ntra Sra Del Prado S.c',
  'Sedimacar, Sl': 'Sedimacar, Sl',
  'Momo Oil': 'Momo Oil',
  Granaoil: 'Granaoil',
  'E.s. La Central': 'E.s. La Central',
  'E.s. Dehesa Boyal': 'E.s. Dehesa Boyal',
  'Grupo Criado': 'Grupo Criado',
  Jtfuel: 'Jtfuel',
  'Coop. San Jose': 'Coop. San Jose',
  'Es Salorino': 'Es Salorino',
  'Sdad Coop San Lucas Del Torno': 'Sdad Coop San Lucas Del Torno',
  'Petrol 13': 'Petrol 13',
  Copreca: 'Copreca',
  'Agrupacion Coop. Valle Del Jerte': 'Agrupacion Coop. Valle Del Jerte',
  'Coop. El Pedroso': 'Coop. El Pedroso',
  'Bfuel Algeciras': 'Bfuel Algeciras',
  'La Calle Del Motor': 'La Calle Del Motor',
  Argomar: 'Argomar',
  'Es El Peral': 'Es El Peral',
  Garrucho: 'Garrucho',
  'Estacion De Servicios Jedula': 'Estacion De Servicios Jedula',
  'Gacosur Barbate': 'Gacosur Barbate',
  'E.s. El Fresno': 'E.s. El Fresno',
  'Gafisur Palmones': 'Gafisur Palmones',
  'E.s. Santa Ana De La Janda': 'E.s. Santa Ana De La Janda',
  'E.s.benalup': 'E.s.benalup',
  Radiotaxi: 'Radiotaxi',
  'E.s. La Almoraima': 'E.s. La Almoraima',
  Easyfuel: 'Easyfuel',
  Lavaoil: 'Lavaoil',
  'Axxon Red, Sl': 'Axxon Red, Sl',
  'Qp Chipiona': 'Qp Chipiona',
  Petrolia: 'Petrolia',
  'Sca. Ntra. Sra. De Las Virtudes': 'Sca. Ntra. Sra. De Las Virtudes',
  'Centro De Lavado La Zorrera Sl': 'Centro De Lavado La Zorrera Sl',
  'Gacosur Jerez': 'Gacosur Jerez',
  Cnj: 'Cnj',
  Jimenoil: 'Jimenoil',
  'E.s. La Lonja': 'E.s. La Lonja',
  Q8easy: 'Q8easy',
  'B.p.': 'B.p.',
  'E.s. Tres Caminos': 'E.s. Tres Caminos',
  Codes: 'Codes',
  'Bfuel Campamento': 'Bfuel Campamento',
  'U.s. Torreguadiaro': 'U.s. Torreguadiaro',
  'Eess Ntra Sra De Los Milagros': 'Eess Ntra Sra De Los Milagros',
  Tarifuel: 'Tarifuel',
  'Tarifa Oil': 'Tarifa Oil',
  'Petroliferos De Tahivilla': 'Petroliferos De Tahivilla',
  'E.s El Barrial S.l': 'E.s El Barrial S.l',
  'Go Ubrique': 'Go Ubrique',
  Dp: 'Dp',
  'Pistoil Vejer': 'Pistoil Vejer',
  'Gacosur Villamartin': 'Gacosur Villamartin',
  'Area De Servicio La Palmera': 'Area De Servicio La Palmera',
  12241: '12241',
  'Estacion De Servicio Liebana S.l': 'Estacion De Servicio Liebana S.l',
  'E.s. Marja': 'E.s. Marja',
  'E.s. Somahoz': 'E.s. Somahoz',
  'Talleres Y Servicios Villegar': 'Talleres Y Servicios Villegar',
  'Valle De Liendo': 'Valle De Liendo',
  'Area De Servicio Pamanes': 'Area De Servicio Pamanes',
  'Petroleos De Cudeyo': 'Petroleos De Cudeyo',
  'Eess La Cavada': 'Eess La Cavada',
  'E.s.solbas': 'E.s.solbas',
  Expomarina: 'Expomarina',
  'E.s. Argomilla': 'E.s. Argomilla',
  'Gasolinera Alisal': 'Gasolinera Alisal',
  'Nueva Alisal': 'Nueva Alisal',
  'Area De Servicio Torrelavega': 'Area De Servicio Torrelavega',
  'Ruyco Petrol': 'Ruyco Petrol',
  Combuscan: 'Combuscan',
  Coopnostra: 'Coopnostra',
  'Castell Xivert': 'Castell Xivert',
  Gial: 'Gial',
  Laytor: 'Laytor',
  Lafuente: 'Lafuente',
  'Coop.sagrado Corazon De Altura': 'Coop.sagrado Corazon De Altura',
  'Grupo Maicas Peiro': 'Grupo Maicas Peiro',
  Eurofuel: 'Eurofuel',
  Benihort: 'Benihort',
  Fm: 'Fm',
  Ceeoil: 'Ceeoil',
  '3gs Combustibles': '3gs Combustibles',
  'Coop. La Union De Benlloch': 'Coop. La Union De Benlloch',
  'Global Hrv': 'Global Hrv',
  'E.s. Hermanos Simo': 'E.s. Hermanos Simo',
  'Eess De Cabanes 40 Pies': 'Eess De Cabanes 40 Pies',
  'La Ribera De Cabanes': 'La Ribera De Cabanes',
  'Bencinas Borriol': 'Bencinas Borriol',
  Monfort: 'Monfort',
  'Bencinas Mestrets': 'Bencinas Mestrets',
  'American Petrol': 'American Petrol',
  'E.s.mibecosl': 'E.s.mibecosl',
  'E.s. Balmapa': 'E.s. Balmapa',
  'Coop. Divina Pastora De Jerica': 'Coop. Divina Pastora De Jerica',
  Lucena: 'Lucena',
  'Carburantes Cooperativos': 'Carburantes Cooperativos',
  Carla: 'Carla',
  'Foresma Desarrollos Sl': 'Foresma Desarrollos Sl',
  Rallo: 'Rallo',
  'Ondamita Oil': 'Ondamita Oil',
  'Road Runner': 'Road Runner',
  Gmr: 'Gmr',
  'Vcc Oropesa': 'Vcc Oropesa',
  'Coop.san Juan De San Juan De Moro': 'Coop.san Juan De San Juan De Moro',
  'Es Zaragoza': 'Es Zaragoza',
  'Coop. Nª Sª De La Asuncion De Soneja': 'Coop. Nª Sª De La Asuncion De Soneja',
  'Transportes Rodolfo Y Ventura': 'Transportes Rodolfo Y Ventura',
  Randero: 'Randero',
  'Coop. Isidro La Vall': 'Coop. Isidro La Vall',
  'Vcc La Vall': 'Vcc La Vall',
  'Coop. Agricola Sant Bartomeu De Vilanova D\'alcolea': 'Coop. Agricola Sant Bartomeu De Vilanova D\'alcolea',
  Ecozoil: 'Ecozoil',
  Macmaoil: 'Macmaoil',
  'Gas Solis': 'Gas Solis',
  'El Cristo': 'El Cristo',
  'Teb  24/7': 'Teb  24/7',
  'E.s. San Gregorio': 'E.s. San Gregorio',
  'Mancha Centro': 'Mancha Centro',
  'Tradilo Inversiones Sl': 'Tradilo Inversiones Sl',
  Gasoleosjuco: 'Gasoleosjuco',
  Coovimag: 'Coovimag',
  'Unidad De Servicio': 'Unidad De Servicio',
  'P G E Hijos': 'P G E Hijos',
  'Combustibles Criptana,sl': 'Combustibles Criptana,sl',
  Travesa: 'Travesa',
  'Ee Ss Puente Del Ave': 'Ee Ss Puente Del Ave',
  'La Loma': 'La Loma',
  'Grupo Translogistica': 'Grupo Translogistica',
  Wetroad: 'Wetroad',
  'Grupo Logistico Codaitrans': 'Grupo Logistico Codaitrans',
  'Coop. Los Pozos': 'Coop. Los Pozos',
  'Los Donceles Energy': 'Los Donceles Energy',
  Delfincarfuel: 'Delfincarfuel',
  'Coop. Los Llanos': 'Coop. Los Llanos',
  'Autolavados Y Carburantes Alse Sl': 'Autolavados Y Carburantes Alse Sl',
  Roderoil: 'Roderoil',
  'Galan De Membrilla': 'Galan De Membrilla',
  'Castillo De Montiel': 'Castillo De Montiel',
  'Ee.ss Valle Piqueras': 'Ee.ss Valle Piqueras',
  'Gp Energia': 'Gp Energia',
  'An Energeticos - Piedrabuena': 'An Energeticos - Piedrabuena',
  Duramax: 'Duramax',
  'E.s. Logafuell': 'E.s. Logafuell',
  'Carburantes Blue': 'Carburantes Blue',
  'Petrol Red': 'Petrol Red',
  'J.utrilla': 'J.utrilla',
  'Estacion De Carburantes San Bartolome Apostol': 'Estacion De Carburantes San Bartolome Apostol',
  'Translogistica Marin Sa': 'Translogistica Marin Sa',
  Ch2m: 'Ch2m',
  'E.s.sto.domingo De Guzman': 'E.s.sto.domingo De Guzman',
  Cotrato: 'Cotrato',
  'Easy Fuel': 'Easy Fuel',
  'Stop Oil': 'Stop Oil',
  Sertyman: 'Sertyman',
  Es: 'Es',
  'E.e.s.s. Mira': 'E.e.s.s. Mira',
  'E.s. Mira': 'E.s. Mira',
  Mellado: 'Mellado',
  Chm: 'Chm',
  'E.s. Vadillo': 'E.s. Vadillo',
  Taray: 'Taray',
  'Puerta Los Pedroches': 'Puerta Los Pedroches',
  Fito: 'Fito',
  'R.r. Estacion De Servicio': 'R.r. Estacion De Servicio',
  Area117: 'Area117',
  Motolux: 'Motolux',
  'Fc Go': 'Fc Go',
  'Fc Petroleos': 'Fc Petroleos',
  'Almazaras De La Subbetica': 'Almazaras De La Subbetica',
  'La Chica': 'La Chica',
  'El Empalme': 'El Empalme',
  'La Lagunilla': 'La Lagunilla',
  Riosol: 'Riosol',
  'La Salud': 'La Salud',
  'Carburantes Premium': 'Carburantes Premium',
  'E.s. El Granadal': 'E.s. El Granadal',
  'Petroil Energy Granadal': 'Petroil Energy Granadal',
  'E.s. Gestinco Cardador': 'E.s. Gestinco Cardador',
  'La Lancha': 'La Lancha',
  'Petroil Energy Azahara': 'Petroil Energy Azahara',
  'Petroil Energy La Granja': 'Petroil Energy La Granja',
  'E.s. Las Cuevas': 'E.s. Las Cuevas',
  'Petroil Energy Torrecilla': 'Petroil Energy Torrecilla',
  Rspetrol: 'Rspetrol',
  'E.s. Reto Ahorro': 'E.s. Reto Ahorro',
  'Hispania De Carburantes': 'Hispania De Carburantes',
  Petroglop: 'Petroglop',
  'El Poligono': 'El Poligono',
  'Santo Cristo': 'Santo Cristo',
  Hruiz: 'Hruiz',
  Gpb: 'Gpb',
  Secsa: 'Secsa',
  'Rs Petrol': 'Rs Petrol',
  'El Carmen': 'El Carmen',
  'E.s. Mª Auxiliadora': 'E.s. Mª Auxiliadora',
  Petrovap: 'Petrovap',
  Prodenergy: 'Prodenergy',
  'Energy La Variante': 'Energy La Variante',
  Mirasierra: 'Mirasierra',
  'F.del Moral': 'F.del Moral',
  Suylavir: 'Suylavir',
  'Yaryma 1': 'Yaryma 1',
  Gsm: 'Gsm',
  'E.s. La Hermida': 'E.s. La Hermida',
  'Carbugal Meicende': 'Carbugal Meicende',
  'E.s.teiraboa': 'E.s.teiraboa',
  'Servicios Poligono Piadela': 'Servicios Poligono Piadela',
  'Estacion De Servicio Piadela Fase Iii': 'Estacion De Servicio Piadela Fase Iii',
  Corredoiras: 'Corredoiras',
  'Gasoleos San Benito': 'Gasoleos San Benito',
  Gasuma: 'Gasuma',
  'Carbugal Laraxe': 'Carbugal Laraxe',
  'Carbugal A Barcala': 'Carbugal A Barcala',
  Cetanoil: 'Cetanoil',
  'Estacion De Servicio Sigras': 'Estacion De Servicio Sigras',
  'Mingacho Oil': 'Mingacho Oil',
  Mingacho: 'Mingacho',
  'Carbugal Carballo': 'Carbugal Carballo',
  'Estacion De Servicio Tabeaio': 'Estacion De Servicio Tabeaio',
  'Estacion De Servicio A Trabe': 'Estacion De Servicio A Trabe',
  'Carbugal Cee': 'Carbugal Cee',
  'Carbugal Coristanco': 'Carbugal Coristanco',
  Digana: 'Digana',
  'Carbugal Coliseum': 'Carbugal Coliseum',
  'Miramar Oil': 'Miramar Oil',
  'Carbugal A Grela': 'Carbugal A Grela',
  'Carbugal Los Rosales': 'Carbugal Los Rosales',
  'Tns Motor': 'Tns Motor',
  'Carbugal Alvedro': 'Carbugal Alvedro',
  Disa_shell: 'Disa_shell',
  'E.s. Irixoa - Irigas Group': 'E.s. Irixoa - Irigas Group',
  'E.s Vidueiros': 'E.s Vidueiros',
  'Cerqueda Sl': 'Cerqueda Sl',
  Yethi: 'Yethi',
  'Fuel Y Furioso': 'Fuel Y Furioso',
  'E.s. Santa Rita': 'E.s. Santa Rita',
  'Estacion De Servicio O Val': 'Estacion De Servicio O Val',
  Barcia: 'Barcia',
  'Estacion De Servicio Ordes': 'Estacion De Servicio Ordes',
  'Agraria Comarcal Ordes Scg': 'Agraria Comarcal Ordes Scg',
  'E.s. Pedron': 'E.s. Pedron',
  'Combustibles Rio Eume': 'Combustibles Rio Eume',
  'Estacion De Servicio Pena De Malate': 'Estacion De Servicio Pena De Malate',
  'Agro Do Forno': 'Agro Do Forno',
  'Carbugal Sada': 'Carbugal Sada',
  'Grupo Pena': 'Grupo Pena',
  'Lag Xallas': 'Lag Xallas',
  'Manzaneda - Sionlla': 'Manzaneda - Sionlla',
  'La Carabela': 'La Carabela',
  Eessbenza: 'Eessbenza',
  'Myg Gasoleos': 'Myg Gasoleos',
  'E.s. Vilaboa': 'E.s. Vilaboa',
  'Car Oil': 'Car Oil',
  'Grupo Barambio': 'Grupo Barambio',
  'Noalles Y Balanza': 'Noalles Y Balanza',
  'R4 San Millan': 'R4 San Millan',
  'Estacion De Servicio Cardenete': 'Estacion De Servicio Cardenete',
  'E.s. La Cuesta': 'E.s. La Cuesta',
  'U.s. David Collado': 'U.s. David Collado',
  'E.s. Virgen De La Soledad': 'E.s. Virgen De La Soledad',
  Andresoil: 'Andresoil',
  'E.s.hpg': 'E.s.hpg',
  Cointrans: 'Cointrans',
  'U.s Gasoleos Guillen S.l': 'U.s Gasoleos Guillen S.l',
  'E.s. Monasor': 'E.s. Monasor',
  'Sumergy -  Grupo Sertranin': 'Sumergy -  Grupo Sertranin',
  'Arba Sa': 'Arba Sa',
  'Nt.s.de Manjavacas S.coop De Clm': 'Nt.s.de Manjavacas S.coop De Clm',
  'La Gaviota Gasolinera 24 Horas': 'La Gaviota Gasolinera 24 Horas',
  Superoil: 'Superoil',
  'E.s.quintanar': 'E.s.quintanar',
  'E.s. Valero 24 H': 'E.s. Valero 24 H',
  'Ven Y Ven Oil': 'Ven Y Ven Oil',
  'Gasoleos La Parrilla': 'Gasoleos La Parrilla',
  'Ntro. Padre Jesus Nazareno, Sdad. Coop De Clm': 'Ntro. Padre Jesus Nazareno, Sdad. Coop De Clm',
  'Eess Rotonda': 'Eess Rotonda',
  'Manzanares Ruiz': 'Manzanares Ruiz',
  Dilamor: 'Dilamor',
  'Virgen Urbanos': 'Virgen Urbanos',
  'E.s. Valenciano Medina': 'E.s. Valenciano Medina',
  'E.s.d Villanueva De La Jara': 'E.s.d Villanueva De La Jara',
  Matalara: 'Matalara',
  Urkide: 'Urkide',
  Urepel: 'Urepel',
  Gacela: 'Gacela',
  Zabaleta: 'Zabaleta',
  Bidasoil: 'Bidasoil',
  Gasoleoa: 'Gasoleoa',
  Merkaoil: 'Merkaoil',
  Gexa: 'Gexa',
  'Gasogas Olaberria': 'Gasogas Olaberria',
  'Alkartasuna Usurbilgo Baserritarren Kooperatiba': 'Alkartasuna Usurbilgo Baserritarren Kooperatiba',
  'E.s.avinyonet': 'E.s.avinyonet',
  'Full  Energy Bellcaire D\'emporda': 'Full  Energy Bellcaire D\'emporda',
  Aoil: 'Aoil',
  Petroservice: 'Petroservice',
  Oilarea: 'Oilarea',
  Rabell: 'Rabell',
  Aneuoil: 'Aneuoil',
  'E.s.mex': 'E.s.mex',
  'Epsilon Plus': 'Epsilon Plus',
  'Cervia Oil': 'Cervia Oil',
  'Empuries Oils L\'escala': 'Empuries Oils L\'escala',
  'Petrofigueres Nf': 'Petrofigueres Nf',
  'Tramuntana Figueres': 'Tramuntana Figueres',
  Servico: 'Servico',
  'Mifascet,slu': 'Mifascet,slu',
  Tramuntana: 'Tramuntana',
  Dyneff: 'Dyneff',
  Escuderoil: 'Escuderoil',
  'And Go': 'And Go',
  'Eurowag Figueres': 'Eurowag Figueres',
  Geckoil: 'Geckoil',
  Mdiesel: 'Mdiesel',
  'Zona Zero': 'Zona Zero',
  Servioil: 'Servioil',
  Petroestany: 'Petroestany',
  'Calsina Carre': 'Calsina Carre',
  Sergasa: 'Sergasa',
  'Regencos Oil': 'Regencos Oil',
  'Enco Sant Jordi': 'Enco Sant Jordi',
  'Riu D\'or': 'Riu D\'or',
  'Sym Sarria': 'Sym Sarria',
  'E.s. Tossa De Mar': 'E.s. Tossa De Mar',
  Fluid: 'Fluid',
  'Full Energy - Viladamat': 'Full Energy - Viladamat',
  Avanza: 'Avanza',
  Juncadiesel: 'Juncadiesel',
  'Andaluza De Transportes Sca': 'Andaluza De Transportes Sca',
  Lerfu: 'Lerfu',
  Gasolinera: 'Gasolinera',
  Carbualga: 'Carbualga',
  Gm10: 'Gm10',
  'E.s.el Molino Alhendin': 'E.s.el Molino Alhendin',
  'Granasol San Pablo': 'Granasol San Pablo',
  'E.s. El Molino Atarfe I': 'E.s. El Molino Atarfe I',
  'E.s. Petronachil - Los Alamos': 'E.s. Petronachil - Los Alamos',
  'E.s. El Molino Atarfe Dos': 'E.s. El Molino Atarfe Dos',
  Carba: 'Carba',
  'Ee Ss Los Carrasquillas': 'Ee Ss Los Carrasquillas',
  Castril: 'Castril',
  'Combustibles Cht Cijuela': 'Combustibles Cht Cijuela',
  'A.aguaza': 'A.aguaza',
  'Los Villares': 'Los Villares',
  'Carburantes A92': 'Carburantes A92',
  'E.s. Valle Zahor': 'E.s. Valle Zahor',
  'Am Plus': 'Am Plus',
  'Las Gabias': 'Las Gabias',
  'San Lazaro': 'San Lazaro',
  'Fenix Oil': 'Fenix Oil',
  'Eess Gasoleos Ferrer S.l': 'Eess Gasoleos Ferrer S.l',
  'El Grupo Sca': 'El Grupo Sca',
  'Egea Huescar': 'Egea Huescar',
  96053: '96053',
  'Centro Sur': 'Centro Sur',
  Cosafra: 'Cosafra',
  'La Vega': 'La Vega',
  Cht: 'Cht',
  'E.s. Virgen Del Agua': 'E.s. Virgen Del Agua',
  'E.s. Lemans': 'E.s. Lemans',
  'Estacion De Servicio Valle De Lecrin': 'Estacion De Servicio Valle De Lecrin',
  'Comb.quintana Quintana': 'Comb.quintana Quintana',
  'E.s. El Molino Maracena': 'E.s. El Molino Maracena',
  'E.s. Villasol': 'E.s. Villasol',
  'E.s Molvizar, S.l': 'E.s Molvizar, S.l',
  'Haxx Puerto De Motril': 'Haxx Puerto De Motril',
  'E.s. Granasol': 'E.s. Granasol',
  'Suministros San Anton': 'Suministros San Anton',
  'E.s Mirador De Poqueira': 'E.s Mirador De Poqueira',
  'Lubricantes Martin': 'Lubricantes Martin',
  'Area De Servicio De La Peza': 'Area De Servicio De La Peza',
  Sps: 'Sps',
  'Airport Granada': 'Airport Granada',
  'E.s. Petronachil': 'E.s. Petronachil',
  'E.s Jesmar': 'E.s Jesmar',
  Gaia: 'Gaia',
  'Anaya Sl': 'Anaya Sl',
  Alameda: 'Alameda',
  'E.s. La Rural': 'E.s. La Rural',
  Maroil: 'Maroil',
  'Los Angeles': 'Los Angeles',
  'Area 117': 'Area 117',
  'Fuentecilla I': 'Fuentecilla I',
  'Asb Energia': 'Asb Energia',
  Btp: 'Btp',
  Gesgasoleo: 'Gesgasoleo',
  Sutacon: 'Sutacon',
  'E.s. La Carrasca': 'E.s. La Carrasca',
  Gasolivia: 'Gasolivia',
  'Ntra.sra. De La Estrella,s.c.a': 'Ntra.sra. De La Estrella,s.c.a',
  Jucofuel: 'Jucofuel',
  Higueroil: 'Higueroil',
  'Tycsa Aqualon': 'Tycsa Aqualon',
  'Gas Auto': 'Gas Auto',
  'Tycsa Trafico Pesado': 'Tycsa Trafico Pesado',
  Tycsa: 'Tycsa',
  Ch: 'Ch',
  'Vibe Carburantes': 'Vibe Carburantes',
  Cobella: 'Cobella',
  'E.s. Aguamarina': 'E.s. Aguamarina',
  Costaoil: 'Costaoil',
  Agd: 'Agd',
  Mogueroil: 'Mogueroil',
  Platero: 'Platero',
  'Estacion De Servicio La Fontanilla': 'Estacion De Servicio La Fontanilla',
  Pateroil: 'Pateroil',
  'Sat Condado': 'Sat Condado',
  Virsur: 'Virsur',
  Gondelcu: 'Gondelcu',
  Sumalca: 'Sumalca',
  'E.s. La Cruz Del Gallo': 'E.s. La Cruz Del Gallo',
  Sumaroil: 'Sumaroil',
  'Zufregas S.l': 'Zufregas S.l',
  'Sc Sierra De Alcubierre': 'Sc Sierra De Alcubierre',
  'Virgen De La Corona': 'Virgen De La Corona',
  'Estacion De Servicio': 'Estacion De Servicio',
  Csc: 'Csc',
  'Estacion Servicio Bonet Sl': 'Estacion Servicio Bonet Sl',
  'E.s.bellavista': 'E.s.bellavista',
  'Shop Area Benas': 'Shop Area Benas',
  'Coop. San Marcos': 'Coop. San Marcos',
  Agropienso: 'Agropienso',
  'Coop. San Lorenzo': 'Coop. San Lorenzo',
  'Coop.fonz': 'Coop.fonz',
  Agropecuaria: 'Agropecuaria',
  'Area Del Bajo Cinca': 'Area Del Bajo Cinca',
  'Sat 3068': 'Sat 3068',
  'Estacion Servicio Municipal': 'Estacion Servicio Municipal',
  Exibox: 'Exibox',
  'Dip Energy': 'Dip Energy',
  'Hiper Oil': 'Hiper Oil',
  Orangutan: 'Orangutan',
  'Coop.  Las Ontinas': 'Coop.  Las Ontinas',
  'Sclas Energeticos': 'Sclas Energeticos',
  'Cereales Ramiro Gruas': 'Cereales Ramiro Gruas',
  Santalecinaganadera: 'Santalecinaganadera',
  'Combustibles La Litera': 'Combustibles La Litera',
  Esc: 'Esc',
  'E.s.sibierre': 'E.s.sibierre',
  '23eso68f': '23eso68f',
  Gcl: 'Gcl',
  'E.s. Europa': 'E.s. Europa',
  'E.s. Iliturgi': 'E.s. Iliturgi',
  'E.s. Vegas De Triana': 'E.s. Vegas De Triana',
  'El Balcon De Andalucia': 'El Balcon De Andalucia',
  Pozonuevo: 'Pozonuevo',
  'Area De Servicio El Delfin': 'Area De Servicio El Delfin',
  Seguroil: 'Seguroil',
  'S.c.a. Ntra. Sra. De La Cabeza': 'S.c.a. Ntra. Sra. De La Cabeza',
  Chevron: 'Chevron',
  'E.s. Paseo De La Virgen': 'E.s. Paseo De La Virgen',
  'E.s. Guarroman': 'E.s. Guarroman',
  Jaimapark: 'Jaimapark',
  'E.s.las Piletas': 'E.s.las Piletas',
  Energy24h: 'Energy24h',
  Ghnplus: 'Ghnplus',
  'E.s.  Jamilena': 'E.s.  Jamilena',
  'E.s. Canava': 'E.s. Canava',
  'S.c.a. Sanagustin': 'S.c.a. Sanagustin',
  'Gasolineras Hf': 'Gasolineras Hf',
  'E.s. La Loperana': 'E.s. La Loperana',
  'Stmo Cristo De La Expiracion': 'Stmo Cristo De La Expiracion',
  'Oleocampo, S.coop.and. De 2º Grado': 'Oleocampo, S.coop.and. De 2º Grado',
  Donjimeno: 'Donjimeno',
  'E S Petroandalus': 'E S Petroandalus',
  Dieselprix: 'Dieselprix',
  'Euroil Cuatrocaminos': 'Euroil Cuatrocaminos',
  'Euroil Larecta': 'Euroil Larecta',
  'Aceites Guadalquivir': 'Aceites Guadalquivir',
  'Alija Energia': 'Alija Energia',
  Petroas: 'Petroas',
  Carbucrial: 'Carbucrial',
  'E.s.cargosa': 'E.s.cargosa',
  Servigordon: 'Servigordon',
  'Gasoleos Villager': 'Gasoleos Villager',
  Cedyc: 'Cedyc',
  'Compostra Oil': 'Compostra Oil',
  Lisarminia: 'Lisarminia',
  'E.s. Trabadelo': 'E.s. Trabadelo',
  'Saenz De Miera Sl': 'Saenz De Miera Sl',
  Villager: 'Villager',
  'Alto Leon': 'Alto Leon',
  Distrol: 'Distrol',
  'Servi Ager': 'Servi Ager',
  'Coop Albatarrec': 'Coop Albatarrec',
  'Cereales Torremorell': 'Cereales Torremorell',
  Arbequina: 'Arbequina',
  'Farre Oil': 'Farre Oil',
  'Coopservice D\'artesa': 'Coopservice D\'artesa',
  'Coop.aspa': 'Coop.aspa',
  Bltr: 'Bltr',
  Sorigue: 'Sorigue',
  'Coop Bellcaire': 'Coop Bellcaire',
  Nadal: 'Nadal',
  'E.s.arenes Bellpuig': 'E.s.arenes Bellpuig',
  'E.s Sant Isidre': 'E.s Sant Isidre',
  'Segre Oil': 'Segre Oil',
  'Seroil  Energy': 'Seroil  Energy',
  Xopluc: 'Xopluc',
  'Autoservei M3': 'Autoservei M3',
  'Coop. Ivars': 'Coop. Ivars',
  'Estacion Boya': 'Estacion Boya',
  'Verge Loreto': 'Verge Loreto',
  'Gasolinera Low Cost': 'Gasolinera Low Cost',
  Transegre: 'Transegre',
  'Benzinera Martinet': 'Benzinera Martinet',
  'Autoservei 24 H': 'Autoservei 24 H',
  'Agraria De Miralcamp': 'Agraria De Miralcamp',
  Valenti: 'Valenti',
  'Estacio Servei Oliana': 'Estacio Servei Oliana',
  'Ondina Del Segre': 'Ondina Del Segre',
  Mapisaoil: 'Mapisaoil',
  'E.s. Sant Guim': 'E.s. Sant Guim',
  'E.s. Sant Ramon': 'E.s. Sant Ramon',
  'Sav Serveis': 'Sav Serveis',
  'E.s.termens': 'E.s.termens',
  'E.s.mas': 'E.s.mas',
  'Renova Oil': 'Renova Oil',
  'F.a.les Planes': 'F.a.les Planes',
  Vallfogonina: 'Vallfogonina',
  'E. S. Betren': 'E. S. Betren',
  Cando: 'Cando',
  Ariosa: 'Ariosa',
  'Aira Oil': 'Aira Oil',
  'E.s. Guntin': 'E.s. Guntin',
  'Gasoleos Ceao': 'Gasoleos Ceao',
  'Gasoleos De Monforte': 'Gasoleos De Monforte',
  7345: '7345',
  Ultreya: 'Ultreya',
  'O Xeixo,s.coop Galega  Oil': 'O Xeixo,s.coop Galega  Oil',
  'Caxigo S Coop Galega': 'Caxigo S Coop Galega',
  Campa: 'Campa',
  Abelleira: 'Abelleira',
  Tex: 'Tex',
  'E.s. Poligono': 'E.s. Poligono',
  'E.s. Camba': 'E.s. Camba',
  Energy: 'Energy',
  'Confor Auto': 'Confor Auto',
  Combus: 'Combus',
  Redexis: 'Redexis',
  Solner: 'Solner',
  Embocador: 'Embocador',
  Delfioil: 'Delfioil',
  'Gasoleos Sierra Oeste,sl': 'Gasoleos Sierra Oeste,sl',
  Merodio: 'Merodio',
  'Gasoleos Daganzo': 'Gasoleos Daganzo',
  'Carbugal Fuenlabrada': 'Carbugal Fuenlabrada',
  Petrojarama: 'Petrojarama',
  Bagarciva: 'Bagarciva',
  'Esteba Rivas': 'Esteba Rivas',
  Gc: 'Gc',
  'Energreen Mobility': 'Energreen Mobility',
  'Oil A42': 'Oil A42',
  Easyrepost: 'Easyrepost',
  Spa360: 'Spa360',
  'Oil+': 'Oil+',
  'Madrid Wetaxi Glp': 'Madrid Wetaxi Glp',
  Edv: 'Edv',
  Morafuel: 'Morafuel',
  Olanca: 'Olanca',
  Servifacil: 'Servifacil',
  Od06: 'Od06',
  Cab: 'Cab',
  'Store Fuel': 'Store Fuel',
  'Green Gas': 'Green Gas',
  'Super Gasoil': 'Super Gasoil',
  'Loucos  A.s. El Toro': 'Loucos  A.s. El Toro',
  Basic: 'Basic',
  Castroil: 'Castroil',
  'S.c.a. Ntra. Sra. De Monsalud': 'S.c.a. Ntra. Sra. De Monsalud',
  'Gafisur Antequera': 'Gafisur Antequera',
  'Agraria Del Turon': 'Agraria Del Turon',
  'Asjileiva Bnamargosa': 'Asjileiva Bnamargosa',
  'Adisadi Velez': 'Adisadi Velez',
  'Petrosur Jq43': 'Petrosur Jq43',
  'E.s Bahia De Casares': 'E.s Bahia De Casares',
  'E.s. Secadero': 'E.s. Secadero',
  'La Trocha': 'La Trocha',
  'E.s.maridi': 'E.s.maridi',
  'E.s. Saladillo': 'E.s. Saladillo',
  'E.s Nerja': 'E.s Nerja',
  'Vladoil Riogordo': 'Vladoil Riogordo',
  'Aorva Group': 'Aorva Group',
  'Estacion Servicio Teba': 'Estacion Servicio Teba',
  Maxoil: 'Maxoil',
  'Los Remedios': 'Los Remedios',
  'La Inmaculada': 'La Inmaculada',
  'Carburantes Clavero - San Sebastian': 'Carburantes Clavero - San Sebastian',
  Trops: 'Trops',
  'E.s. Siles Aguilera': 'E.s. Siles Aguilera',
  'Olivarera Trabuco': 'Olivarera Trabuco',
  'Aceites Los Romanes': 'Aceites Los Romanes',
  'Los Calzones': 'Los Calzones',
  'E.s. Montepinar': 'E.s. Montepinar',
  'Raspaoil E.s.aguilas': 'Raspaoil E.s.aguilas',
  'C.p.g. La Marina': 'C.p.g. La Marina',
  Expoaguilas: 'Expoaguilas',
  Secotrans: 'Secotrans',
  'Transportes Gregorio': 'Transportes Gregorio',
  'Centro Diesel Combustibles Murcianos': 'Centro Diesel Combustibles Murcianos',
  'Lo Sola': 'Lo Sola',
  'Juan Martinez Saura': 'Juan Martinez Saura',
  'El Guadalentin': 'El Guadalentin',
  'Dialco El Prado': 'Dialco El Prado',
  Hlh: 'Hlh',
  'La Archenera': 'La Archenera',
  'Us Rosemur': 'Us Rosemur',
  Camper: 'Camper',
  Cobuco: 'Cobuco',
  Eurosol: 'Eurosol',
  'E.s Petrogaz': 'E.s Petrogaz',
  'Gasoleos Calasparra': 'Gasoleos Calasparra',
  Euroloma: 'Euroloma',
  Tradic: 'Tradic',
  'E.s La Almudema': 'E.s La Almudema',
  Adridan: 'Adridan',
  Palusoil: 'Palusoil',
  'Ee.ss. Aljorra': 'Ee.ss. Aljorra',
  'Cabezo Ventura': 'Cabezo Ventura',
  'Buenos Aires': 'Buenos Aires',
  Aparcadolores: 'Aparcadolores',
  'Peninsula Cartagena': 'Peninsula Cartagena',
  Vedicar: 'Vedicar',
  'U.s. Transmaravillas': 'U.s. Transmaravillas',
  Canaraflor: 'Canaraflor',
  'Los Torraos': 'Los Torraos',
  Sermuco: 'Sermuco',
  'E.s. Premier': 'E.s. Premier',
  'Almendras Murcianas': 'Almendras Murcianas',
  'El Marino': 'El Marino',
  'La Pintaica': 'La Pintaica',
  'El Baden': 'El Baden',
  'Venta La Petra': 'Venta La Petra',
  Europa: 'Europa',
  'El Remolino': 'El Remolino',
  'Petrolorca - El Pantano': 'Petrolorca - El Pantano',
  Burgos: 'Burgos',
  Lorbus: 'Lorbus',
  'Ee.ss Aguaderas': 'Ee.ss Aguaderas',
  'Jose Garcia Guillen': 'Jose Garcia Guillen',
  'Petrolorca - E.s. La Campana': 'Petrolorca - E.s. La Campana',
  M: 'M',
  'Agroter Sat  Nº1936': 'Agroter Sat  Nº1936',
  'Gasmor E Hijos S.l': 'Gasmor E Hijos S.l',
  'E.s. Papa Ali': 'E.s. Papa Ali',
  'Global Tank La Serreta': 'Global Tank La Serreta',
  'Gps.molina': 'Gps.molina',
  Apellan: 'Apellan',
  'El Romeral': 'El Romeral',
  Intercon: 'Intercon',
  'E.s.hnos.blazquez Sl': 'E.s.hnos.blazquez Sl',
  'Los Llanos Ii': 'Los Llanos Ii',
  Sotramul: 'Sotramul',
  Frucimu: 'Frucimu',
  Europetrol: 'Europetrol',
  Valeroil: 'Valeroil',
  'Thader I': 'Thader I',
  'Cabezo Gas': 'Cabezo Gas',
  'E.s. Monteagudo': 'E.s. Monteagudo',
  Repostamax: 'Repostamax',
  'Casillas De Combustibles Sl': 'Casillas De Combustibles Sl',
  'Transgallego Logistic Sl': 'Transgallego Logistic Sl',
  'Omega Sangonera': 'Omega Sangonera',
  'El Limonar': 'El Limonar',
  Alq: 'Alq',
  'La Noria': 'La Noria',
  'Airemar Ii': 'Airemar Ii',
  'Omega Espinardo': 'Omega Espinardo',
  'Airemar I': 'Airemar I',
  'Suministros Pliego S.l': 'Suministros Pliego S.l',
  'Grupo Eurogalmar': 'Grupo Eurogalmar',
  'Global Tank': 'Global Tank',
  'Parking De Camiones': 'Parking De Camiones',
  'El Porras': 'El Porras',
  Hortamira: 'Hortamira',
  'Hermanos Navarro': 'Hermanos Navarro',
  Clay: 'Clay',
  'Grupo Hefame': 'Grupo Hefame',
  'Atranscar Ctm': 'Atranscar Ctm',
  'La Hita- El Molino': 'La Hita- El Molino',
  Jcc: 'Jcc',
  F21: 'F21',
  'Fuentes Logistics Quality': 'Fuentes Logistics Quality',
  Coato: 'Coato',
  'Area De Servicio Agetrans': 'Area De Servicio Agetrans',
  'E.s. La Santa': 'E.s. La Santa',
  Ts: 'Ts',
  'Jpg Petrol': 'Jpg Petrol',
  'Raspaoil E.s. Yecla': 'Raspaoil E.s. Yecla',
  'An Energeticos - Ablitas': 'An Energeticos - Ablitas',
  'Coop Ezkibel': 'Coop Ezkibel',
  'An Energeticos - Andosilla Bodega San Sebastian': 'An Energeticos - Andosilla Bodega San Sebastian',
  'La Rotxa Ansoain': 'La Rotxa Ansoain',
  'Mg Talluntxe': 'Mg Talluntxe',
  'An Energeticos - Los Arcos': 'An Energeticos - Los Arcos',
  'An Energeticos - Arguedas': 'An Energeticos - Arguedas',
  'S.coop. San Esteban': 'S.coop. San Esteban',
  'E.s.la Recta': 'E.s.la Recta',
  'An Energeticos - Artajona': 'An Energeticos - Artajona',
  'An Energeticos - Azagra': 'An Energeticos - Azagra',
  'Talleres Arrubla': 'Talleres Arrubla',
  'An Energeticos - Arizkun': 'An Energeticos - Arizkun',
  'Nafar Mendi': 'Nafar Mendi',
  Nafaroil: 'Nafaroil',
  'An Energeticos - Berbinzana': 'An Energeticos - Berbinzana',
  Abycer: 'Abycer',
  'Transportes Cruz': 'Transportes Cruz',
  'An Energeticos - Cadreita': 'An Energeticos - Cadreita',
  'An Energeticos - Caparroso': 'An Energeticos - Caparroso',
  Carcar: 'Carcar',
  'Combustibles Piudo': 'Combustibles Piudo',
  'An Energeticos - Carcastillo': 'An Energeticos - Carcastillo',
  'Bodega Ntra. Sra. Del Romero': 'Bodega Ntra. Sra. Del Romero',
  'An Energeticos - Caseda': 'An Energeticos - Caseda',
  'An Energeticos - Castejon': 'An Energeticos - Castejon',
  Atugas: 'Atugas',
  'An Energeticos - Cintruenigo Bodega Cirbonera': 'An Energeticos - Cintruenigo Bodega Cirbonera',
  'Bm Complet': 'Bm Complet',
  'Sertelgas,sl': 'Sertelgas,sl',
  'An Energeticos - Cortes': 'An Energeticos - Cortes',
  'An Energeticos - Urroz': 'An Energeticos - Urroz',
  'Igoa Y Patxi Sl': 'Igoa Y Patxi Sl',
  'An Energeticos - Sarriguren': 'An Energeticos - Sarriguren',
  'Del Villar Energia': 'Del Villar Energia',
  'An Energeticos - Falces': 'An Energeticos - Falces',
  'An Energeticos - Funes 2': 'An Energeticos - Funes 2',
  'An Energeticos - Funes': 'An Energeticos - Funes',
  'An Energeticos - Huarte': 'An Energeticos - Huarte',
  'Bi Ahizpak': 'Bi Ahizpak',
  Sarasate: 'Sarasate',
  Marisa: 'Marisa',
  'An Energeticos - Lerin': 'An Energeticos - Lerin',
  'Neumaticos Bidasoa': 'Neumaticos Bidasoa',
  'Transportes Bidasoa': 'Transportes Bidasoa',
  'An Energeticos - Lumbier': 'An Energeticos - Lumbier',
  Asle: 'Asle',
  Luzaide: 'Luzaide',
  'An Energeticos - Melida': 'An Energeticos - Melida',
  'An Energeticos - Mendavia': 'An Energeticos - Mendavia',
  'An Energeticos - Mendigorria': 'An Energeticos - Mendigorria',
  'An Energeticos - Miranda De Arga': 'An Energeticos - Miranda De Arga',
  'Transportes Azpiroz': 'Transportes Azpiroz',
  'Bidasoa Combustibles': 'Bidasoa Combustibles',
  'Transportes Sakana Scl': 'Transportes Sakana Scl',
  'An Energeticos - Olite': 'An Energeticos - Olite',
  Agip: 'Agip',
  Argi: 'Argi',
  'S. Coop. Litxarra': 'S. Coop. Litxarra',
  'An Energeticos - Peralta': 'An Energeticos - Peralta',
  'An Energeticos - Ribaforada': 'An Energeticos - Ribaforada',
  'Agricola San Blas': 'Agricola San Blas',
  'An Energeticos - Sanguesa': 'An Energeticos - Sanguesa',
  'An Energeticos - Sesma': 'An Energeticos - Sesma',
  'An Energeticos - Tafalla': 'An Energeticos - Tafalla',
  Tiebas: 'Tiebas',
  'An Energeticos - Tudela 1': 'An Energeticos - Tudela 1',
  Petrotudela: 'Petrotudela',
  'An Energeticos - Tudela 2': 'An Energeticos - Tudela 2',
  'Tudefrigo Logistica': 'Tudefrigo Logistica',
  'E.s. Bardenas': 'E.s. Bardenas',
  Alpe: 'Alpe',
  'An Energeticos - Valtierra': 'An Energeticos - Valtierra',
  'Combustibles Villafranca': 'Combustibles Villafranca',
  'An Energeticos - Villafranca': 'An Energeticos - Villafranca',
  'An Energeticos - Yerri': 'An Energeticos - Yerri',
  Petrobal: 'Petrobal',
  'Petrol Lentellais': 'Petrol Lentellais',
  Latequin: 'Latequin',
  'Eess Maceda': 'Eess Maceda',
  'O Surtidor': 'O Surtidor',
  'E.s. O Viso': 'E.s. O Viso',
  'E. S. O Pino': 'E. S. O Pino',
  'J.l E Hijos': 'J.l E Hijos',
  'E.s. 2001': 'E.s. 2001',
  'Petrol A Rua': 'Petrol A Rua',
  Superfuel: 'Superfuel',
  'Ourensana De Petroleos Sl': 'Ourensana De Petroleos Sl',
  Fina: 'Fina',
  'Los Linares': 'Los Linares',
  'An Energeticos - Car Carrion': 'An Energeticos - Car Carrion',
  Cobasguar: 'Cobasguar',
  'Petrocorner Los Chopos': 'Petrocorner Los Chopos',
  Suances: 'Suances',
  'Las Lagunas': 'Las Lagunas',
  'Tgas Sardina Del Norte': 'Tgas Sardina Del Norte',
  'Puerto Rico, S.a': 'Puerto Rico, S.a',
  'Canary Green Corner, Sl': 'Canary Green Corner, Sl',
  'H2exagon Norte': 'H2exagon Norte',
  'H2go Corralejo': 'H2go Corralejo',
  'H2go Morro Jable': 'H2go Morro Jable',
  'H2exagon Las Torres': 'H2exagon Las Torres',
  'H2exagon Escaleritas': 'H2exagon Escaleritas',
  'H2go Muelle Chico': 'H2go Muelle Chico',
  Mercasosa: 'Mercasosa',
  'H2exagon Jinamar': 'H2exagon Jinamar',
  'Combustibles Canarios': 'Combustibles Canarios',
  'Marina Rubicon': 'Marina Rubicon',
  Ckm: 'Ckm',
  'E.s.valeixe': 'E.s.valeixe',
  'Loimil Gas': 'Loimil Gas',
  Coafor: 'Coafor',
  Cn: 'Cn',
  Sanchilan: 'Sanchilan',
  Gasoleos: 'Gasoleos',
  Peinador: 'Peinador',
  'El Sol': 'El Sol',
  'A Chan De Amoedo': 'A Chan De Amoedo',
  'Ere Area De Servicio': 'Ere Area De Servicio',
  'E.s. Peibar Barrantes': 'E.s. Peibar Barrantes',
  'O Rodo': 'O Rodo',
  Lowxen: 'Lowxen',
  'Aira Silleda': 'Aira Silleda',
  Outletui: 'Outletui',
  Bye: 'Bye',
  Galea: 'Galea',
  'Ee.ss. Camanzo': 'Ee.ss. Camanzo',
  'E.s.el Salgueiral': 'E.s.el Salgueiral',
  Royo: 'Royo',
  Isatir: 'Isatir',
  'An Energeticos - Aldeanueva': 'An Energeticos - Aldeanueva',
  'An Energeticos - Autol': 'An Energeticos - Autol',
  'E.s. Rio Linares': 'E.s. Rio Linares',
  'Carburantes Rioja': 'Carburantes Rioja',
  Nalda: 'Nalda',
  'Estaciones Arnedo': 'Estaciones Arnedo',
  Cocavica: 'Cocavica',
  Bernal: 'Bernal',
  'Las Torres': 'Las Torres',
  Bejaroil: 'Bejaroil',
  'E.s. Cabrerizos': 'E.s. Cabrerizos',
  Aranpino: 'Aranpino',
  Renaccia: 'Renaccia',
  Iberfuel: 'Iberfuel',
  'Area De Servicios Y Transportes Guijuelo Sl': 'Area De Servicios Y Transportes Guijuelo Sl',
  'Monte La Reina': 'Monte La Reina',
  'Hidro&gar.2': 'Hidro&gar.2',
  'Ronda Oeste': 'Ronda Oeste',
  'Combustibles Trabanca': 'Combustibles Trabanca',
  'Ecu Villares': 'Ecu Villares',
  Usc: 'Usc',
  'Eumogas, Sl': 'Eumogas, Sl',
  'H2exagon Arafo': 'H2exagon Arafo',
  'Tgas La Hidalga': 'Tgas La Hidalga',
  'Tgas Arona': 'Tgas Arona',
  'Tgas Las Galletas': 'Tgas Las Galletas',
  'Tgas Las Caletillas': 'Tgas Las Caletillas',
  'E.s. La Caleta': 'E.s. La Caleta',
  'Tgas Santa Catalina': 'Tgas Santa Catalina',
  'El Escobonal': 'El Escobonal',
  'Tgas La Gorvorana': 'Tgas La Gorvorana',
  'Estacion De Servicios El Mirador': 'Estacion De Servicios El Mirador',
  'Tgas El Rosario': 'Tgas El Rosario',
  'Tgas Montesdeoca': 'Tgas Montesdeoca',
  'Tgas Las Mercedes': 'Tgas Las Mercedes',
  'San Sebastian': 'San Sebastian',
  'Tgas Tacoronte': 'Tgas Tacoronte',
  'Tgas Tegueste': 'Tgas Tegueste',
  'Estacion  Servicio Chipude': 'Estacion  Servicio Chipude',
  'An Energeticos - Carbonero El Mayor Mesenor': 'An Energeticos - Carbonero El Mayor Mesenor',
  'An Energeticos - Cuellar Glus I': 'An Energeticos - Cuellar Glus I',
  'Carlos Diez Segovia': 'Carlos Diez Segovia',
  'Andres Tejedor E Hijos': 'Andres Tejedor E Hijos',
  'An Energeticos - Fuentesauco Glus I': 'An Energeticos - Fuentesauco Glus I',
  Gar: 'Gar',
  Navatrans: 'Navatrans',
  Bravoil: 'Bravoil',
  'Agrocomercial Higuera': 'Agrocomercial Higuera',
  Polo: 'Polo',
  Semutransa: 'Semutransa',
  'Llorsoil- E. S. Valverde': 'Llorsoil- E. S. Valverde',
  Novaoil: 'Novaoil',
  'Hijos De Oliva': 'Hijos De Oliva',
  'E.s. Magdaoil': 'E.s. Magdaoil',
  Ilipamagna: 'Ilipamagna',
  Oroil: 'Oroil',
  'Sierra Del Terril Sca': 'Sierra Del Terril Sca',
  'M4 Repost': 'M4 Repost',
  'Qp Almensilla': 'Qp Almensilla',
  'La Juliana': 'La Juliana',
  'Qp Bollullos': 'Qp Bollullos',
  Aybcarburantes: 'Aybcarburantes',
  Lavabu: 'Lavabu',
  'Red Ahorro': 'Red Ahorro',
  7267: '7267',
  'Ruta 4': 'Ruta 4',
  'San Teodomiro': 'San Teodomiro',
  'E.s.los Molinillos': 'E.s.los Molinillos',
  Burbujas: 'Burbujas',
  'Operadora Sevillana': 'Operadora Sevillana',
  'E.s. El Rocio': 'E.s. El Rocio',
  Sol: 'Sol',
  'E.s. Rodalabota': 'E.s. Rodalabota',
  'Coniyde Doshermanas': 'Coniyde Doshermanas',
  Capi: 'Capi',
  Genil: 'Genil',
  'Best Fuel': 'Best Fuel',
  C2i: 'C2i',
  Petrosand: 'Petrosand',
  'E.s. Atenas': 'E.s. Atenas',
  Petroplus: 'Petroplus',
  A2d: 'A2d',
  'Gacosur Mairena': 'Gacosur Mairena',
  'Mairena Agricola,s.c.a': 'Mairena Agricola,s.c.a',
  Autolavados: 'Autolavados',
  Petrobike: 'Petrobike',
  'El Olivo': 'El Olivo',
  Volaroil: 'Volaroil',
  'Combustibles Y Lavado Los Palacios': 'Combustibles Y Lavado Los Palacios',
  'La Movil Grupo Puertas': 'La Movil Grupo Puertas',
  'Sca Agraria San Anton': 'Sca Agraria San Anton',
  'Oleand, S.coop.and': 'Oleand, S.coop.and',
  'A&b': 'A&b',
  'E.s. La Catria': 'E.s. La Catria',
  Masfuel: 'Masfuel',
  'Emc Red Power 24': 'Emc Red Power 24',
  Sajardines: 'Sajardines',
  'E.s. Parraga': 'E.s. Parraga',
  Apj: 'Apj',
  'E.s. Su Eminencia': 'E.s. Su Eminencia',
  'Ronda Norte': 'Ronda Norte',
  'Nueva Calonge': 'Nueva Calonge',
  'Qp Nervion': 'Qp Nervion',
  'Gacosur Parsi': 'Gacosur Parsi',
  Pertroprix: 'Pertroprix',
  Petroamarilla: 'Petroamarilla',
  'Karlavado.com': 'Karlavado.com',
  Redcaroil: 'Redcaroil',
  Petrouya: 'Petrouya',
  'Canges Del Hoyo': 'Canges Del Hoyo',
  'E.s.vistalegre': 'E.s.vistalegre',
  'E.s El Palmar': 'E.s El Palmar',
  'E.s. Maria Auxiliadora': 'E.s. Maria Auxiliadora',
  'Combustibles Villamanrique': 'Combustibles Villamanrique',
  'San Juan Bautista S Coop And': 'San Juan Bautista S Coop And',
  'Tala Foods': 'Tala Foods',
  'E.s. El Valle': 'E.s. El Valle',
  Gamar: 'Gamar',
  Oruca: 'Oruca',
  'Ghc Soria': 'Ghc Soria',
  'Sin Determinar': 'Sin Determinar',
  Dpm: 'Dpm',
  Eureka: 'Eureka',
  Copiso: 'Copiso',
  'Jayomi Serveis': 'Jayomi Serveis',
  Multigrupo: 'Multigrupo',
  Gasamp: 'Gasamp',
  'Tronova Energia': 'Tronova Energia',
  'Cecatrans Transport & Logistics, S.l': 'Cecatrans Transport & Logistics, S.l',
  'Tradilo Inversiones': 'Tradilo Inversiones',
  'Coop. La Galera': 'Coop. La Galera',
  'La Botiga Del Sindicat': 'La Botiga Del Sindicat',
  'Coop. Agricola Sant Isidre': 'Coop. Agricola Sant Isidre',
  'Lorry Petrol': 'Lorry Petrol',
  Entreauto: 'Entreauto',
  Montepio: 'Montepio',
  'Agricola Del Camp Santa Barbara': 'Agricola Del Camp Santa Barbara',
  'Vinicola De Sarral, Sccl': 'Vinicola De Sarral, Sccl',
  'Joan Oils': 'Joan Oils',
  'Sin Asignar': 'Sin Asignar',
  Bionet: 'Bionet',
  Covilalba: 'Covilalba',
  Copvilar: 'Copvilar',
  'E.s. Aguaviva': 'E.s. Aguaviva',
  Gba: 'Gba',
  'E.s De Alfambra': 'E.s De Alfambra',
  'La Calandina': 'La Calandina',
  Sanicoop: 'Sanicoop',
  Subigas: 'Subigas',
  'Coop.cretas': 'Coop.cretas',
  'Coop.san Antonio': 'Coop.san Antonio',
  'E.s.orihuela Del Tremedal': 'E.s.orihuela Del Tremedal',
  'San Fabian Y San Sabastian': 'San Fabian Y San Sabastian',
  Seragas: 'Seragas',
  Civera: 'Civera',
  'Super Cash Vimar': 'Super Cash Vimar',
  Agrimartin: 'Agrimartin',
  Scoaval: 'Scoaval',
  Petrocasarrubios: 'Petrocasarrubios',
  'E.s. El Desvio': 'E.s. El Desvio',
  Star24h: 'Star24h',
  'Combustibles Huerta': 'Combustibles Huerta',
  Hoila: 'Hoila',
  'Santa Ana': 'Santa Ana',
  Carbunor: 'Carbunor',
  'Hermanos Fernandez Garcia Sa': 'Hermanos Fernandez Garcia Sa',
  Ecosuministros: 'Ecosuministros',
  'T.cruz': 'T.cruz',
  Petrocoes: 'Petrocoes',
  'Petroleos Martin Corporation': 'Petroleos Martin Corporation',
  'Moewe Talvar': 'Moewe Talvar',
  'Scb Talavera': 'Scb Talavera',
  'Oramba Estaciones De Servicio': 'Oramba Estaciones De Servicio',
  'U.s.torrehierro': 'U.s.torrehierro',
  'Itv La Floresta': 'Itv La Floresta',
  'J. Utrilla': 'J. Utrilla',
  Delfinoil: 'Delfinoil',
  'Gfm Ca': 'Gfm Ca',
  Petrolcar: 'Petrolcar',
  'Ecoil Levante': 'Ecoil Levante',
  Lowcost24h: 'Lowcost24h',
  Starma: 'Starma',
  'Els Gafarrons': 'Els Gafarrons',
  'Bz Alboraya': 'Bz Alboraya',
  Azeroil: 'Azeroil',
  'El Canari': 'El Canari',
  'Petromax De Levante': 'Petromax De Levante',
  'Vcc Alfafar': 'Vcc Alfafar',
  'Coop El Porvenir': 'Coop El Porvenir',
  Coagri: 'Coagri',
  'Vcc Alginet': 'Vcc Alginet',
  Criel: 'Criel',
  S2: 'S2',
  Coagal: 'Coagal',
  'Ccooperativa De Alpuente': 'Ccooperativa De Alpuente',
  'Coop. Sant Bernat': 'Coop. Sant Bernat',
  'Alzicoop Carburants': 'Alzicoop Carburants',
  Anna: 'Anna',
  'Carburantes Y Servicios Ayora Sl': 'Carburantes Y Servicios Ayora Sl',
  'La Ayorense Carburantes': 'La Ayorense Carburantes',
  'Lowcost Benaguacil': 'Lowcost Benaguacil',
  'E.s. Benetuser': 'E.s. Benetuser',
  Beniarjo: 'Beniarjo',
  'Sat Beata Ines': 'Sat Beata Ines',
  'Canso Carbuantes Benimodo': 'Canso Carbuantes Benimodo',
  'Multimarca Combustibles': 'Multimarca Combustibles',
  'Centre La Vereda': 'Centre La Vereda',
  'Vc Energia': 'Vc Energia',
  Agricar: 'Agricar',
  'Vcc Carlet': 'Vcc Carlet',
  'E.s. El Cortijo': 'E.s. El Cortijo',
  'E.s. La Ponderosa': 'E.s. La Ponderosa',
  Coopcarlet: 'Coopcarlet',
  'Estacio De Servici El Regaixo': 'Estacio De Servici El Regaixo',
  'Vcc Catarroja': 'Vcc Catarroja',
  'Cheste Agraria': 'Cheste Agraria',
  'La Union Chivana': 'La Union Chivana',
  'Pegasolina Star': 'Pegasolina Star',
  'E.s. Daimus': 'E.s. Daimus',
  'Optyme Self System': 'Optyme Self System',
  'Campoenguera Coop V': 'Campoenguera Coop V',
  'Grupo Cirugeda Colom Sl': 'Grupo Cirugeda Colom Sl',
  'Vcc Gandia': 'Vcc Gandia',
  Unigesco: 'Unigesco',
  Saforoil: 'Saforoil',
  'V.c.': 'V.c.',
  Servicoop: 'Servicoop',
  'El Valle': 'El Valle',
  'E.s. San Coronado': 'E.s. San Coronado',
  Edetagas: 'Edetagas',
  Atunoil: 'Atunoil',
  'Motoracing 81': 'Motoracing 81',
  'Grupo Laratrans': 'Grupo Laratrans',
  Petromax: 'Petromax',
  Ribercost: 'Ribercost',
  'Auroservicio Cirugeda 24 H': 'Auroservicio Cirugeda 24 H',
  'E.s.metroarte Moncada': 'E.s.metroarte Moncada',
  'Bon Servici': 'Bon Servici',
  'Coarval Carburants': 'Coarval Carburants',
  'Centre La Alqueria': 'Centre La Alqueria',
  Ros: 'Ros',
  'Estacion Servicio': 'Estacion Servicio',
  Cosotrans: 'Cosotrans',
  'Mas Del Pi': 'Mas Del Pi',
  'Coop V Onteniense': 'Coop V Onteniense',
  'E.s. Metroarte': 'E.s. Metroarte',
  'Miguel Pi': 'Miguel Pi',
  Eldisser: 'Eldisser',
  'Estacion Inter Patty': 'Estacion Inter Patty',
  'Mas Gasoil': 'Mas Gasoil',
  'Anymore Transport, Sl': 'Anymore Transport, Sl',
  'Tc Campillo': 'Tc Campillo',
  Dieself: 'Dieself',
  Coopic: 'Coopic',
  Puzol: 'Puzol',
  Copuzol: 'Copuzol',
  Gaspuig: 'Gaspuig',
  Yeno: 'Yeno',
  'Industrial Gil Folgado Sl': 'Industrial Gil Folgado Sl',
  Virosque: 'Virosque',
  Chemaballester: 'Chemaballester',
  Sinerlogis: 'Sinerlogis',
  'E.s. Oliveral A3,sl': 'E.s. Oliveral A3,sl',
  'Servitransport La Vall': 'Servitransport La Vall',
  'U.s. Asg Sl': 'U.s. Asg Sl',
  'Carburantes Sagunto': 'Carburantes Sagunto',
  Octaplus: 'Octaplus',
  Rep: 'Rep',
  Sendra: 'Sendra',
  Optyme: 'Optyme',
  Gasoprix: 'Gasoprix',
  A2oil: 'A2oil',
  'Coop Silla': 'Coop Silla',
  Gasopotenz: 'Gasopotenz',
  'E.s.visa': 'E.s.visa',
  Futurgasoil: 'Futurgasoil',
  'Landete Gimeno': 'Landete Gimeno',
  'E.s.titaguas S.l': 'E.s.titaguas S.l',
  'Certecsion Sl': 'Certecsion Sl',
  'Gas Del Mas': 'Gas Del Mas',
  'Fenix Gestion': 'Fenix Gestion',
  'La Baronia De Turis Coop V': 'La Baronia De Turis Coop V',
  'E.s. Sur': 'E.s. Sur',
  'E.s. La Torreta': 'E.s. La Torreta',
  Taxco: 'Taxco',
  Carrrefour: 'Carrrefour',
  'Lb Energia': 'Lb Energia',
  'Benzinera Vilamarxant': 'Benzinera Vilamarxant',
  'E.s. Villalonga': 'E.s. Villalonga',
  'Eess Toscana': 'Eess Toscana',
  Masip: 'Masip',
  Gax: 'Gax',
  'Scva Virgen Desamparados': 'Scva Virgen Desamparados',
  'San Agustin': 'San Agustin',
  'Cocope S.coop': 'Cocope S.coop',
  'E.s. Real': 'E.s. Real',
  'An Energeticos, S.l. - Esguevillas De Esgueva': 'An Energeticos, S.l. - Esguevillas De Esgueva',
  'Ion+': 'Ion+',
  'Sugasyl Sl': 'Sugasyl Sl',
  'Lowcost Medina': 'Lowcost Medina',
  'Coop Cocol': 'Coop Cocol',
  'E.s.pedrajas': 'E.s.pedrajas',
  'Los Ceas': 'Los Ceas',
  Servatra: 'Servatra',
  Svg: 'Svg',
  Eoil: 'Eoil',
  'An Energeticos - Jaramiel': 'An Energeticos - Jaramiel',
  'Del Olmo Hermanos': 'Del Olmo Hermanos',
  Tencar: 'Tencar',
  Texacoil: 'Texacoil',
  Espanoil: 'Espanoil',
  'E.s. El Pino': 'E.s. El Pino',
  'Coordinacion Agraria Sa': 'Coordinacion Agraria Sa',
  '|> Enertrix <|': '|> Enertrix <|',
  Mg: 'Mg',
  Haxx: 'Haxx',
};
