export enum FUEL_NAME {
  ADBLUE = 'AdBlue',
  CNG = 'Compressed Natural Gas (CNG)',
  GASOLINE_2_STROKE = '2 Stroke Gasoline',
  GASOLINE_95 = 'Gasoline 95',
  GASOLINE_98 = 'Gasoline 98',
  DIESEL = 'Diesel',
  DIESEL_FARM = 'Farm Diesel',
  DIESEL_HEAT = 'Heat Diesel',
  DIESEL_PREMIUM = 'Diesel Premium',
  ETHANOL = 'Ethanol',
  HYDROGEN = 'Hydrogen',
  LNG = 'Liquefied Natural Gas (LNG)',
  LPG = 'Liquefied Petroleum Gas (LPG)',
  UNKNOWN = 'Unknown',
}
